### ISSUE TITLE
Demo workflow is invalid

### ISSUE THREAD

**Issue by rpenny125** [zowe/zlux-workflow#17]
There is a demo folder in zlux-workflow, with a workflow definition xml file, storyboard-new.xml

1. It comes through the checkout/build process as ebcdic, when UTF-8 is more natural for z/OSMF
2. The copyright comment at the beginning breaks xml validation
3. The embedded plugins mentioned in the descriptions are "experimental" plugins that are not included in Zowe, so the embedding should be updated to refer to plugins included in zowe (such as com.ibm.atlas.atlasUSS)

**Comment by philippe-richard** [comment]
looks like after changing  the new homepage to /ZLUX/plugins/org.zowe.zlux.bootstrap/web/ (as recommended by @Sean Grady it solved my pb.  I'm running zowe 0.9.3 now and i can see all my workflows, and even add new ones.

**Comment by 1000TurquoisePogs** [comment]
1: fixed.
2: fixed.
3: good idea.
